# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.CharField(blank=True, max_length=11, null=True)),
                ('dob', models.DateField()),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('fees_paid', models.IntegerField()),
                ('pending_fees', models.IntegerField(blank=True, null=True)),
                ('fully_paid', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
