# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_count', models.IntegerField(default=0)),
                ('A', models.BooleanField(default=False)),
                ('a_allocated_to', models.CharField(blank=True, max_length=10, null=True)),
                ('B', models.BooleanField(default=False)),
                ('b_allocated_to', models.CharField(blank=True, max_length=10, null=True)),
                ('C', models.BooleanField(default=False)),
                ('c_allocated_to', models.CharField(blank=True, max_length=10, null=True)),
                ('D', models.BooleanField(default=False)),
                ('d_allocated_to', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('ac', 'AC'), ('non-ac', 'NON-AC')], default='non-ac', max_length=20)),
                ('roomno', models.CharField(max_length=5)),
                ('fully_allocated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-roomno'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
    ]
