# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 9, 30, 5, 3, 31, 703345, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
