# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 9, 30, 8, 10, 2, 127268, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
